[project]
name = "feedboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rga", email = "r.gaziano@gmail.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
feedboard = "feedboard:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
